### ISSUE TITLE
Possibly add Double asterisk operator `**`, for exponentiation, from ECMAScript 2016 (ES7)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/PatEL#3]
The source code of Iosevka uses `Math.pow` in a lot of places. This could potentially clean up this expression wherever it shows up.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation

**Comment by be5invis** [comment]
You can always use `define-operator`, like

```
define-operator "**" 150 "right" : syntax-rules
    `(@l ** @r) `[Math.pow @l @r]
```
